export const RESET_INGREDIENTS = "RESET_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";

export const LOAD_ORDER_START = "LOAD_ORDER_START";
export const RESET_ORDER_LOADING = "RESET_ORDER_LOADING";
export const LOAD_ORDER_SUCCESS = "LOAD_ORDER_SUCCESS";
export const LOAD_ORDER_FAIL = "LOAD_ORDER_FAIL";
export const SET_MESSAGE = "SET_MESSAGE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOG_OUT = "LOG_OUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
