export const RESET_INGREDIENTS = "RESET_INGREDIENTS";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
// export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const RESET_ORDER_LOADING = "RESET_ORDER_LOADING";
export const LOADED_ORDERS = "LOADED_ORDERS";
